name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Clear yarn cache
      run: yarn cache clean
    - name: Install dependencies
      run: |
        yarn config set network-timeout 300000
        yarn install --network-timeout 300000 --no-cache
      env:
        CI: true

    - name: Make Windows installer
      run: yarn make --platform=win32
      env:
        CI: true

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v3
      with:
        name: windows-installer
        path: out/make/**/*.exe